---
title: "Events"
editor: visual
---

## Previous webinars

+------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Date             | Description                                                                                                                                                                                                                          | Recording                                                                                                                                                                            |
+==================+======================================================================================================================================================================================================================================+======================================================================================================================================================================================+
| May 13, 2026     | Teaching Bayesian Statistics in Modern Sports Analytics                                                                                                                                                                              | [Recording](https://us06web.zoom.us/rec/share/1VLV0Qj3Dqvh0pADBbkQQoFD7tFch80uT4ArMR7sHMRNko-TEI6lxN-cpD6xhHg.qe5dJJNZP-TCF45b?startTime=1778688102000 Passcode: up+=R04G)           |
|                  |                                                                                                                                                                                                                                      |                                                                                                                                                                                      |
|                  | Speaker: Ron Yurko                                                                                                                                                                                                                   | Link to [slides](https://docs.google.com/presentation/d/1EnnpevqNiICJQg00E44w5HcoMFcoKB1fpxtGj4KjRqQ/edit?usp=sharing)                                                               |
+------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| December 7, 2023 | Panel about Teaching Bayesian Methods in Psychology, featuring panelists Sonja Winter, E.J. Wagenmakers, and Joachim Vandekerckhove.                                                                                                 | [Recording](https://us06web.zoom.us/rec/share/tNB9iHxA6G0r_Qpl3alK7u83-BZHPpQrGhH1MTBWr-CyQl9mWJDRYdt75RkZjQNc.VSyb9D6e6tOGRv8M?startTime=1701968510000)                             |
+------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| June 8, 2023     | Panel featuring authors of the following Bayesian statistics textbooks: *Probability and Bayesian Modeling, Data Analysis using Regression and Multilevel/Hierarchical Models,* and *A First Course in Bayesian Statistical Methods* | [Recording](https://drive.google.com/file/d/1DmX9TiOnSS3WX2u6woJPEUKXsxiuYOjI/view)                                                                                                  |
|                  |                                                                                                                                                                                                                                      |                                                                                                                                                                                      |
|                  | Speakers: Jim Albert, Jennifer Hill, Peter Hoff                                                                                                                                                                                      |                                                                                                                                                                                      |
+------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| March 2, 2023    | Panel featuring authors of the following Bayesian statistics textbooks: *Bayes Rules!, Think Bayes*, and *Bayesian Modeling and Computation in Python.*                                                                              | [Zoom recording](https://us06web.zoom.us/rec/share/rkBCMH8z4w_kc8ObSiRVOW_fmINGpQXDE2ISChxKF-7rB8HSu6V7T1Pc0Z09W7Qd.h7AlSt19iRFvMZAr?startTime=1677773093000%20Passcode:%20#+4MbjB5) |
|                  |                                                                                                                                                                                                                                      |                                                                                                                                                                                      |
|                  | Speakers: Mine Dogucu, Allen Downey, and Ravin Kumar                                                                                                                                                                                 |                                                                                                                                                                                      |
+------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
