---
title: "ISBA - BERaP"
subtitle: "Bayesian Education Research and Practice"
---

BERaP is a section of the International Society for Bayesian Analysis (ISBA). Our aim is to promote Bayes education and research on teaching and learning of Bayesian statistics and statistical literacy at all levels and for any audience.

## Upcoming events

#### [Upcoming Webinars:]{.underline}

+------------------------+-------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Date and Time          | Location                                                                                              | Topic                                                                                                                                                                                                                       |
+========================+=======================================================================================================+=============================================================================================================================================================================================================================+
| Thursday, June 8, 2023 | Zoom                                                                                                  | Panel featuring authors of the following statistics textbooks: *Probability and Bayesian Modeling, Data Analysis using Regression and Multilevel/Hierarchical Models,* and *A First Course in Bayesian Statistical Methods* |
|                        |                                                                                                       |                                                                                                                                                                                                                             |
| 11:00am-12:00pm EDT    | Please register [here](https://us06web.zoom.us/meeting/register/tZEpde2hpjsrHNQPfLgPsNBSua_Lrw_HS5BA) | Speakers: Jim Albert, Jennifer Hill, Peter Hoff                                                                                                                                                                             |
|                        |                                                                                                       |                                                                                                                                                                                                                             |
| (3:00-4:00pm UTC)      |                                                                                                       |                                                                                                                                                                                                                             |
+------------------------+-------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {tbl-colwidths="\[25,20, 55\]"}

Visit our [events](events.qmd) page to see a list of previous webinars.

## Join

Are you interested in being part of the conversation surrounding Bayes education? Join BERaP!

You must first be a [member](https://bayesian.org/membership/joinrenew/) of ISBA. In the *memberships form* portion of the application, you can add your one-year membership to the BERaP (Bayesian Education Research and Practice) section for only \$5 more, or become a lifetime member for \$75.

## About Us

Learn about current [BERaP board members](about.qmd) and [bylaws](bylaws.qmd).
